RUPER/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings    
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path(' ',include('userAuthentication.urls')),
    path('',include('adminPanel.urls')),
    path('',include('users_home.urls')),
    path('',include('cart.urls')),
    path('',include('userprofile.urls')),
    path('',include('order.urls')),
    path('',include('Dashboard.urls')),
    path('',include('coupon.urls')),
    path('',include('wallet.urls')),
    path('',include('products.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.contrib import admin
from django.urls import path
from.import views

urlpatterns = [
    path('cart', views.cart, name='cart'),
    path('add_cart',views.add_cart,name='add_cart'),
    path('updateCart',views.update_cart,name='updateCart'),
    path('item_remove',views.remove_item_cart,name='item_remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('editAddress/<str:id>',views.edit_address,name='editAddress'),
    path('addAddress/',views.add_address,name='addAddress'),
    path('apply_coupon',views.apply_coupon,name='apply_coupon'),
    path('remove_coupon',views.remove_coupon,name='remove_coupon'),
   

]

wallet/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('wallet/',views.wallet,name='wallet'),
    path('add_to_wallet',views.add_to_wallet,name='add_to_wallet'),
    path('update_wallet',views.update_wallet,name='update_wallet'),
]

cart/models.py
from django.db import models
from userAuthentication.models import*
from products.models import *
# 

class Cart(models.Model):
    customuser = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity = models.PositiveBigIntegerField(null=False,blank=False,default=1)
    cart_price = models.PositiveBigIntegerField(default=1)

   
    

order/models.py
from django.db import models
from userAuthentication.models import CustomUser
from userprofile.models import Address
import uuid
from products.models import Products

# Create your models here

class Orders(models.Model):
    order_id = models.CharField(max_length=8,primary_key=True,unique=True,editable=False)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    address = models.ForeignKey(Address,on_delete=models.CASCADE)
    payment_method = models.CharField(max_length=200)
    order_date = models.DateTimeField(auto_now_add=True)
    expected_delivery_date = models.DateField(null=True,blank=True)
    delivered_date = models.DateTimeField(null=True,blank=True)
    quantity = models.PositiveIntegerField()
    total_purchase_amount = models.PositiveIntegerField(default=1)

    def save(self,*args,**kwargs):
        if not self.order_id:
            self.order_id = self.generate_order_id()
        super().save(*args,**kwargs)

    def generate_order_id(self):     
        return str(uuid.uuid4().hex)[:8]
    
    def __str__(self) -> str:
        return f"{self.user}'s order details"
    


class OrdersItem(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    payment_status =models.CharField(max_length=255, default='pending')
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    updated_time = models.DateTimeField(auto_now=True)
    quantity = models.PositiveBigIntegerField()
    price = models.DecimalField(max_digits=10,decimal_places=2)
    total_item_amount = models.PositiveBigIntegerField(default=1)   
    status = models.CharField(default='Order confirmed',max_length=200)
    def total_price(self):
        return self.quantity * self.price

    def __str__(self) -> str:
        return f"{self.order.user}'s {self.product}"    
    






    
    
    
    
  

products/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    is_listed = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Brands(models.Model):
    name = models.CharField(max_length=50)
    is_listed = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name


class Products(models.Model):
    products_name = models.CharField(max_length=50)
    category_id = models.ForeignKey(Category,on_delete=models.CASCADE,)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    brand_id = models.ForeignKey(Brands,on_delete=models.CASCADE)
    is_listed = models.BooleanField(default=True)
    product_offer = models.PositiveIntegerField(default = 0)


    def discounted_price(self):
        discount_percentage = self.product_offer
        if discount_percentage > 0:
            return self.price - ((self.price * discount_percentage) / 100)
        else:
            return self.price
        

    def __str__(self):
        return self.products_name
    
class Image(models.Model):
    image = models.ImageField(upload_to="product_images")
    product_id = models.ForeignKey(Products,on_delete=models.CASCADE)
    

wallet/models.py
from django.db import models
from userAuthentication.models import CustomUser

# Create your models here.

class Wallet(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    transaction_type = models.CharField(max_length=50,null=True)
    transaction_details = models.CharField(max_length=50,null=True)
    amount = models.PositiveIntegerField(default=0)
    balance = models.PositiveBigIntegerField(default=0)
    

cart/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse,HttpResponse
from .models import Cart
from products.models import Products
from decimal import Decimal
from userAuthentication.models import CustomUser
from userprofile.models import Address
from django.contrib import messages
from coupon.models import Coupons, CouponUsage
from django.utils import timezone
from datetime import timedelta, datetime


def add_cart(request):
    if request.method == 'POST':
        quantity = request.POST.get('quantity', 1)
        id = request.POST.get("id") 
        product = Products.objects.get(id = id)

        
        if product.stock >= quantity:
            if Cart.objects.filter(customuser=request.user, product=product).exists():
                return JsonResponse({'success': False})  
            
            # Create or update cart for the user
            cart, created = Cart.objects.get_or_create(
                customuser=request.user, product=product
            )
            price = product.discounted_price()
            cart.quantity = quantity
            cart.cart_price = price * Decimal(quantity)
            cart.save()

            response_data = {
                'success': True,
                'message': 'Item added to cart successfully.'
            }
            return JsonResponse(response_data)
        else:
            return JsonResponse({'success': False, 'message': 'Product out of stock'})

    return JsonResponse({'success': False})

def remove_item_cart(request):  
    if request.method == "POST":
        item_id = request.POST.get('item_id')
        try:
            cart_item = Cart.objects.get(id=item_id)
            cart_item.delete()
            return JsonResponse({"message":"item removed successfully"})
        except Cart.DoesNotExist:
            return JsonResponse({"message": "item not found"}, status=400)
        
    else:
        return JsonResponse({"message": "Invalid request method"}, status=405)     
    


def update_cart(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            user = request.user
            userr = CustomUser.objects.filter(email=user.email).first()
            change = int(request.POST.get('change'))
            cart_id = int(request.POST.get('productId'))
            cart = Cart.objects.get(id=cart_id)
            
            product_obj = Products.objects.get(id=cart.product.id)

            if change == 1:
                if product_obj.stock > cart.quantity:
                    cart.quantity += 1
                    cart.save()
            else:
                if cart.quantity > 1:
                    cart.quantity -= 1
                    cart.save()
                else:
                    cart.quantity = 1
                    cart.save()    

            prodTotal = product_obj.discounted_price() * cart.quantity
            cart.cart_price = prodTotal
            cart.save()     
            cart_items = Cart.objects.filter(customuser=userr)
            total = sum(cart_items.values_list('cart_price',flat=True))
           

            responsData = {
                'updatedQuantity':cart.quantity,
                'prodTotal':prodTotal,
                'totalCartPrice':total
            }
            return JsonResponse(responsData)

    return HttpResponse(status=200)




def cart(request):
    user = request.user
    cart_item = Cart.objects.filter(customuser=user)
    total = sum(cart_item.values_list('cart_price',flat=True))
    context ={
        'cart_item': cart_item,
        'total': total
    }

    return render(request,'userside/cart.html',context)


def checkout(request):
    if request.user.is_authenticated:
        user = request.user
        cart_item = Cart.objects.filter(customuser=user)
        if cart_item.exists():

            userr = request.user
            user = CustomUser.objects.filter(email=userr.email).first()
            address = Address.objects.filter(user=user)
            cart_items = Cart.objects.filter(customuser=user)
            total = sum(cart_items.values_list('cart_price',flat=True))
            coupons = Coupons.objects.filter(is_active=True).filter(expiration_date__gte=timezone.now())
            context = {
                'coupons':coupons,
                'addresses': address,
                'cart_items': cart_items,
                'total': total
            }
            return render(request, 'userside/checkout.html',context)
        else:
            return redirect('cart')
    else:
        return redirect ('signin')


def edit_address(request,id):
    if request.method == 'POST':
        user_address = Address.objects.filter(id=id).first()
        user_address.name = request.POST.get('name')
        user_address.phone = request.POST.get('phone')
        user_address.street_address = request.POST.get('street_address')
        user_address.city = request.POST.get('city')
        user_address.state = request.POST.get('state')
        user_address.pin_code = request.POST.get('pincode')

        user_address.save()
        return redirect('checkout')
        

    user_address = Address.objects.filter(id=id).first()
    return render(request,'userside/editAddress.html',{'user_data':user_address})


def add_address(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        street_address= request.POST.get('street_address')
        city = request.POST.get('city')
        state = request.POST.get('state')
        pincode = request.POST.get('pincode')

        Address.objects.create(user=request.user,name=name, phone=phone, street_address= street_address, city=city, state=state, pin_code=pincode)
        messages.info(request,'Address created successfully')
        return redirect('checkout')
    
    return render(request,'userside/addAddress.html')

def apply_coupon(request):
    if request.method == 'POST':
        email = request.user.email
        user = CustomUser.objects.get(email=email)

        coupon_code = request.POST.get('couponCode')
        coupon_check = Coupons.objects.filter(code=coupon_code ,is_active=True).first()
        if coupon_check:
            if CouponUsage.objects.filter(user=user,coupon=coupon_check).exists():
                return JsonResponse({"error": "Coupon already applied"})
            else:
                if coupon_check.used_count < coupon_check.usage_limit:
                    cart_total = sum(Cart.objects.filter(customuser=user).values_list("cart_price",flat=True))

                    if cart_total >= coupon_check.minimum_purchase:
                        if coupon_check.expiration_date < datetime.now().date():
                            return JsonResponse({"error":"coupon expired"})
                        
                        total = cart_total - coupon_check.discount_value
                        request.session['final_amount'] = int(total)
                        request.session['coupon_Code']  = coupon_code

                        response_data = {
                            "success":"added",
                            "total" : total,
                            "coupon_code" : coupon_code,
                            "discount_amount" : coupon_check.discount_value

                        }
                        coupon_check.used_count +=1
                        coupon_check.save()

                        CouponUsage.objects.create(user=user,coupon = coupon_check)

                        return JsonResponse(response_data)
                    
                    else:
                        return JsonResponse({"error": f"Minimum purchase amount of {round(coupon_check.minimum_purchase)} required"})
                    
                else:

                    return JsonResponse({"error":"This code has reached this maximum limit"})
        else:
            return JsonResponse({"error":"invalid coupon"})
    else:
        return JsonResponse({"error":"invalid request"})       
    

def remove_coupon(request):    
    email = request.user.email
    user = CustomUser.objects.get(email=email)

    coupon_code = request.POST.get("couponCode")
    coupon_check = Coupons.objects.filter(code=coupon_code,is_active=True).first()
    if coupon_check:
            usage_check = CouponUsage.objects.filter(user=user,coupon=coupon_check).first()
            print(usage_check.ordered)
            if usage_check:
                if usage_check.ordered == 1:
                    return JsonResponse({"error":"This Coupon is already applied"})
                else:
                    coupon_check.used_count -= 1
                    coupon_check.save()
                    usage_check.delete()
    total = sum(Cart.objects.filter(customuser=user).values_list('cart_price',flat=True))   
    if 'final_amount' in request.session:
        del request.session['final_amount']
        
    response_data= ({"success":"removed",'total':total})
    
    return JsonResponse(response_data)    

wallet/views.py
from django.shortcuts import render,redirect
from userAuthentication.models import CustomUser
from .models import Wallet
import razorpay
from django.http import JsonResponse

# Create your views here.

def wallet(request):
    email = request.user.email
    user = CustomUser.objects.get(email=email)
    wallet = Wallet.objects.filter(user=user).order_by('-id')
    if wallet:
        balance = wallet.first().balance    
    else:
        balance = 0    

    context = {'balance':balance, 'wallets':wallet}
    
    return render(request,'userside/wallet.html',context)

client = razorpay.Client(auth=("rzp_test_LWQdkfQTzRGUBJ","jXE2IxqDvYVgxJGCbPJM3k71"))


def add_to_wallet(request):
    amount = int(request.POST.get("amount"))* 100
    data = {"amount":amount,'currency':'INR'}
    payment = client.order.create(data=data)

    request.session["amount"] = amount/100

    context = {"success":True,"payment":payment,"payment_id":payment["id"],"amount":amount}

    return JsonResponse(context)


def update_wallet(request):
    email = request.user.email
    amount = request.session["amount"]
    user_name = CustomUser.objects.get(email=email)
    user = Wallet.objects.filter(user=user_name).order_by("-id").first()
    if user:
        balance = user.balance
    else:
        balance = 0   

    new_balance = balance + amount

    Wallet.objects.create(
        user = user_name,
        amount = amount,
        balance = new_balance,
        transaction_type = 'Credit',
        transaction_details = "Added money through razorpay"

    )

    return redirect('wallet')

templates/userside/email_otp.html
<!DOCTYPE html>
<html>

<head>
    <title>Your Email Title</title>
    <style>
        /* Reset some default styles */
        body,
        h1,
        p {
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }

        /* Wrapper for the content */
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        /* Header styles */
        .header {
            background-color: #007bff;
            color: #fff;
            text-align: center;
            padding: 20px;
        }

        /* Content styles */
        .content {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            margin-top: 20px;
        }

        /* OTP section styles */
        .otp-section {
            text-align: center;
            margin-top: 30px;
        }

        /* OTP code styles */
        .otp-code {
            font-size: 36px;
            color: #007bff;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1>Hello!</h1>
            <p>Thank you for using our service.</p>
        </div>
        <div class="content">
            <h2>Your One-Time Password (OTP)</h2>
            <div class="otp-section">
                <span class="otp-code">{{otp}}</span>
            </div>
            <p>
                This code will expire in 5 minutes. Please do not share this with anyone.
            </p>
        </div>
    </div>
</body>

</html>

templates/userside/order_successfull.html
{% extends 'userside/baseuser.html' %}
{% load static %}

{% block style %}
<style>
    /* Custom CSS for order details */
    .order-details {
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 5px;
      box-shadow: 2px 2px 5px #ccc;
      margin: 20px auto;
      max-width: 600px;
      background-color: #fff;
    }
  
    .order-details h2 {
      font-size: 24px;
    }
  
    .order-details p {
      font-size: 16px;
      margin: 10px 0;
    }
  
    .order-item {
      border: 1px solid #ddd;
      padding: 20px;
      border-radius: 10px;
      margin-top: 20px;
      background-color: #f9f9f9;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
  
    .order-item p {
      font-size: 18px;
      margin: 10px 0;
    }
  </style>
{% endblock style %}
{% block content1%} order_successfull {% endblock content1 %}

{% block content %}

<section id="order_placed" class="center_o p-5 bg-light">
    <div class="container-xl">
      <div class="row center_o1 text-center">
        <div class="col-md-12 mb-5">
          <h1 class="p-5"style="color: green;">ORDER PLACED SUCCESSFULLY!!!</h1>
        </div>
      </div>
    </div>
</section>
  
<section id="cart_page" class="cart mb-5">
    <div class="container-xl">
      <div class="order-details">
        <div class="d-flex justify-content-between align-items-center">
        <h2>Order Details</h2>
        <a class="btn btn-outline-secondary" href="{% url 'invoice' %}">View invoice</a>
      </div>
        <p><strong>Order ID:</strong> {{orders.order_id}}</p>
        <p><strong>Order Date:</strong> {{orders.order_date}}</p>
        <p><strong>Order Amount:</strong> {{orders.total_purchase_amount}}</p>
        <p><strong>Shipping Address:</strong> {{orders.address.name}},{{orders.address.city}}, {{orders.address.street_address}}, {{orders.address.phone}} ,{{orders.address.pin_code}}</p>
  
    <!-- Display order items as needed -->
    {% for order in orders.ordersitem_set.all %}
    <div class="order-item">
      <div style="display: flex; align-items: center;">
        <div style="flex: 2;">
          <p><strong>Product Name:</strong> {{order.product.products_name}}</p>
          <p><strong>Quantity:</strong> {{order.quantity}}</p>
           <p><strong>Price:</strong> {{order.price}}</p>
          <p><strong>Subtotal:</strong>{{order.total_item_amount}}</p> 
        </div>
        {% comment %} <div style="flex: 1;">
          <img style=" float:right;" src="" alt="Product A Image" height="150px">
        </div> {% endcomment %}
      </div>
    </div>
    {% endfor %}
      </div>
    </div>
</section>


{% block contentscript%}
{% comment %} //<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script> {% endcomment %}

{% comment %} <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script> {% endcomment %}





{% endblock contentscript%}


{% endblock content %}

templates/userside/shopdetails.html
{% extends 'userside/baseuser.html' %}
{% load static %}
{% block content1%} My Account {% endblock content1 %}
{% block content %}
<div id="site-main" class="site-main">

    <div id="main-content" class="main-content">
        <div id="primary" class="content-area">
            <div id="title" class="page-title">
                <div class="section-container">
                    <div class="content-title-heading">
                        <h1 class="text-title-heading">
                                {{products.products_name}}
                        </h1>
            </div>

            <div id="content" class="site-content" role="main">
                <div class="shop-details zoom" data-product_layout_thumb="scroll" data-zoom_scroll="true" data-zoom_contain_lens="true" data-zoomtype="inner" data-lenssize="200" data-lensshape="square" data-lensborder="" data-bordersize="2" data-bordercolour="#f9b61e" data-popup="false">	
                    <div class="product-top-info">
                        <div class="section-padding">
                            <div class="section-container p-l-r d-flex">
                                <div class="product-images col-lg-7 col-md-12 col-12">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <div class="content-thumbnail-scroll">
                                                <div class="image-thumbnail slick-carousel slick-vertical" data-asnavfor=".image-additional" data-centermode="true" data-focusonselect="true" data-columns4="5" data-columns3="4" data-columns2="4" data-columns1="4" data-columns="4" data-nav="true" data-vertical="&quot;true&quot;" data-verticalswiping="&quot;true&quot;">
                                                    {% for image in products.image_set.all%}
                                                    <div class="img-item slick-slide">
                                                        <span class="img-thumbnail-scroll">
                                                            <img width="600" height="600" src="{{image.image.url}}" alt="">
                                                        </span>
                                                    </div>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>                                      
                                            <div class="col-md-10">
                                                <div class="scroll-image main-image">
                                                    <div class="image-additional slick-carousel" data-asnavfor=".image-thumbnail" data-fade="true" data-columns4="1" data-columns3="1" data-columns2="1" data-columns1="1" data-columns="1" data-nav="true">
                                                        {% for image in products.image_set.all %}
                                                        <div class="img-item slick-slide">
                                                            <!-- Use 'data-zoom-image' attribute to specify the larger image URL for zoom -->
                                                            <img width="900" height="900" src="{{ image.image.url }}" alt="" data-zoom-image="{{ image.image.url }}">
                                                        </div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                    </div>
                                </div>
                                    <div class="product-info col-lg-5 col-md-12 col-12 ">
                                        {% if products.product_offer == 0 %}
                                            <h1 class="title">{{products.products_name}}</h1>
                                        {% else %}
                                            <h1 class="title">{{products.products_name}}-{{products.product_offer}}%OFF</h1>
                                        {% endif %}


                                        <span class="price">
                                            {% comment %} <del aria-hidden="true"><span>$100.00</span></del>  {% endcomment %}
                                            {% if products.product_offer == 0 %}
                                                <ins><span>{{products.price}}</span></ins>
                                            {% else %}  
                                            <ins><span>{{products.discounted_price}}</span></ins>
                                            <s><span>{{products.price}}</span></s>
                                            {% endif %}




                                        </span>
                                        {% comment %} <div class="rating">
                                            <div class="star star-5"></div>
                                            <div class="review-count">
                                                (3<span> reviews</span>)
                                            </div>
                                        </div> {% endcomment %}
                                       <div class="description">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                                        </div> 
                                        
                                        <div class="buttons">
                                            <div class="buttons">
                                                <div class="add-to-cart-wrap">
                                                    <div onclick="addToCart({{products.id}})"class="btn btn-dark" style="width: 450px; text-align: center;">
                                                        <a 
                                                            class="button text-white" tabindex="0"> Add To
                                                            Cart
                                                        </a>
                                                    </div>

                                                </div>
                                            {% comment %} {% comment %} <div class="btn-quick-buy" data-title="Wishlist">
                                                <a href="#" class="product-btn">Buy It Now</a>
                                            </div> {% endcomment %}
                                            {% comment %} <div class="btn-wishlist" data-title="Wishlist">
                                                <a href="#" class="product-btn">Add to wishlist</a>
                                            </div>
                                            <div class="btn-compare" data-title="Compare">
                                                <a href="#" class="product-btn">Compare</a>
                                            </div> {% endcomment %} 
                                        </div>
                                        
                                        
                                        <div class="product-meta">
                                            <span class="sku-wrapper">SKU: <span class="sku">D2300-3-2-2</span></span>
                                            {% for category in  products.category_set.all%}
                                            <span class="posted-in">Category: <a href="" rel="tag"></a>{{category.category.name}}</span>
                                            {% endfor %}
                                            <span class="tagged-as">Tags: <a href="" rel="tag">Hot</a>, <a href="" rel="tag">Trend</a></span>
                                        </div>
                                        <div class="social-share">
                                            <a href="#" title="Facebook" class="share-facebook" target="_blank"><i class="fa fa-facebook"></i>Facebook</a>
                                            <a href="#" title="Twitter" class="share-twitter"><i class="fa fa-twitter"></i>Twitter</a>
                                            <a href="#" title="Pinterest" class="share-pinterest"><i class="fa fa-pinterest"></i>Pinterest</a>
                                        </div>					
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                 
                
                </div>
            </div><!-- #content -->
        </div><!-- #primary -->
        

    </div><!-- #main-content -->
</div>

{% endblock content %}


{% block contentscript%}




<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>

    function getCSRFToken() {
            return $('input[name="csrfmiddlewaretoken"]').val();
        }
        
    function addToCart(id) {
        var csrftoken = getCSRFToken();
        
        $.ajax({
            url: "/add_cart",
            method: "post",
            encoded:true,
            headers: { "X-CSRFToken": csrftoken }, // Set CSRF token in headers
            data: { id: id },
        }).done((data) => {
            if (data.success){
                alert("success")
            }
            else{
                alert("Already in Cart or stock is not available")
            }
            
        }).fail(() => {
            alert('Those who login can only buy the product');
        });
    }
</script>



{% block contentscript1%}
<script src="{% static "libs/elevatezoom/js/jquery.elevatezoom.js" %}"></script>

{% endblock contentscript1%}

{% endblock contentscript%}